name: 'HealthyPunch'
on:
  push:
    branches:
      - main
  schedule:
    - cron: '30 21,4 * * *' #北京时间5点30打卡，和12点半
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: node
jobs:
  Start:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v2
      - name: 'Use Node.js'
        uses: actions/setup-node@v1
        with:
          node-version: '12.18.3'
      - name: 'Run in Nodejs'
        shell: bash
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SCKEY: ${{ secrets.SCKEY }}
        run:
          node HealthyPunch.js
